[project]
name = "aiogram-ext"
version = "0.1.21"
description = ""
authors = []
dependencies = [
    "aiogram>=2.25.1",
    "motor>=3.1.2",
    "parsenv>=0.1.3",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
test = "python tests"

[tool.pdm.scripts._]
env_file = ".env"

[tool.pdm.scripts._.env]
PYTHONPATH = "."
