[tool.poetry]
name = "camerahub-tagger"
version = "0.1.2"
description = "EXIF tagger for CameraHub"
authors = ["Jonathan Gazeley <me@jonathangazeley.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
pyexiv2 = "^2.8.1"
uuid = "^1.30"
deepdiff = "^6.3.0"

[tool.poetry.scripts]
tagger = 'camerahub-tagger.main:main'

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
