[tool.poetry]
name = "flarespy"
version = "0.9.6"
description = "Find flares in TESS light curves"
authors = ["Keyu Xing <kyxing@mail.bnu.edu.cn>"]
license = "MIT"
homepage = "https://github.com/keyuxing/flarespy"
repository = "https://github.com/keyuxing/flarespy"

[tool.poetry.dependencies]
bottleneck = ">=1.3"
lightkurve = ">=2.3"
numba = { version = ">=0.55.2", allow-prereleases = true}
python = ">=3.8"
wotan = ">=1.10"
