[tool.poetry]
name = "openz"
version = "0.1.2"
description = ""
authors = ["Cologler <skyoflw@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "openz"}]
homepage = "https://github.com/Cologler/openz-python"

[tool.poetry.dependencies]
python = "^3.8"
filelock = "^3.12.0"
portalocker = "^2.7.0"
nanoid = "^2.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.263"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.poetry-dynamic-versioning]
enable = false

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
