[tool.poetry]
name = "enhancedocs"
version = "0.5.0a0"
description = "EnhanceDocs Command Line Interface (CLI)"
authors = ["Alvaro Molina <alw3ys@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.29.0"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
