[tool.poetry]
# https://python-poetry.org/docs/pyproject/
# https://github.com/python-poetry/poetry/blob/master/pyproject.toml
name = "nlpia2"
version = "0.0.24"
description = "Natural language processing utilities and examples for the book Natural Language Processing in Action (nlpia) 2nd Edition by Hobson Lane and Maria Dyshel."
# https://choosealicense.com/
license = "AGPLv3"
readme = "README.md"
authors = [
    "Hobson Lane <hobson@tangibleai.com>",
    "Maria Dyshel <maria@tangibleai.com>",
    "Leo Hepis <leo@leohepis.com>",
    "Geoffrey Marshal",
    "Sylvia Lee",
    "Winnie Yeung @dcvionwinnie",
    "Mohammed Dala Ali <mms.dala@gmail.com>",
    "Alex Rosengarten @alxrsngrtn",
    "Jose Robins @jorobins",
    ]
homepage = "https://proai.org"
repository = "https://gitlab.com/tangibleai/nlpia2"
documentation = "https://gitlab.com/tangibleai/nlpia2"
# include = [
#     "README.md",
#     "AUTHORS.md",
#     "CONTRIBUTING.md",
#     "install_editable.sh",
#     "src/nlpia2/data",
#     "src/nlpia2/data/",
#     "src/nlpia2/ch07/cnn/data/disaster-tweets.csv",
#     "src/nlpia2/ch07/cnn/data/trec.csv",
#     ]
# exclude = [
#     ".nlpia2-data/",
#     ]
packages = [
    { include = "nlpia2", from = "src" },
    ]

# https://python-poetry.org/docs/pyproject/#keywords
keywords = ['NLP', 'Natural Language Processing', 'Virtual Assistant', 'chatbot', 'Text Processing', 'Machine Learning', 'Text Mining', 'Deep Learning']
# https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Text Processing :: Linguistic",
  "Topic :: Text Processing",
  "Topic :: Communications",
  "Topic :: Communications :: Chat",
  "Intended Audience :: Education",
]

[tool.poetry.build]
generate-setup-file = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# https://python-poetry.org/docs/pyproject/#scripts
# TODO: rename cnn-classify-text->cnn   and   main.py->cli.py
cnn = "nlpia2.ch07.cnn:main"
adoc_extract = "nlpia2.text_extractors:main"

[tool.poetry.dependencies]
# sentence-transformers-2.2.2 installs: 
#      MarkupSafe-2.1.2 certifi-2022.12.7 charset-normalizer-3.1.0 click-8.1.3
#      cmake-3.26.0 filelock-3.10.2 huggingface-hub-0.13.3 idna-3.4 jinja2-3.1.2
#      joblib-1.2.0 lit-16.0.0 mpmath-1.3.0 networkx-3.0 nltk-3.8.1 numpy-1.24.2
#      nvidia-* packaging-23.0 pillow-9.4.0 pyyaml-6.0 
#      regex-2023.3.22 requests-2.28.2 scikit-learn-1.2.2 scipy-1.10.1 
#      sentencepiece-0.1.97 sympy-1.11.1 threadpoolctl-3.1.0 tokenizers-0.13.2
#      torch-2.0.0 torchvision-0.15.1 tqdm-4.65.0 transformers-4.27.2 triton-2.0.0 typing-extensions-4.5.0
#      urllib3-1.26.15
babel = "^2.11.0"
beautifulsoup4 = "^4.11"
bleach = "^5.0"
bidict = "^0.22"
boto3 = "^1.26"
botocore = "^1.29"
configargparse = "^1.5"
cython = "^0.29"
dataframe-image = "^0.1"
Django = "^4.1"
edit-distance = "^1"
einops = "*"
environment = "^1.0"
gitpython = "^3.1"
graphviz = "^0.20"
h5py = "^3.7.0"
html5lib = "^1.1"
html2text = "^2020.1.16"
jupyter-console = ">=6.4.4"
lxml = "^4.9.1"
m2r = "^0.3"  # [required by Sphinx & m2r](https://github.com/CrossNox/m2r2/issues/40)
# mastodonplus_py = "*"  # broken pypi package `Mastodonplus.py`
# mathtext = {git = "https://gitlab.com/tangibleai/community/mathtext", rev = "main"}
matplotlib = "*"
matplotlib-inline = "*"
meilisearch = "*"
mistune = "*"
nessvec = "*"
# nessvec = {git = "https://gitlab.com/tangibleai/nessvec", rev = "main"}
nltk = "*"
pandas = "*"
parsimonious = "*"
pillow = "^9.3"
pronouncing = "^0.2"
psutil = "^5.9"
pip = ">=22.3.1"
poetry = "^1"
PyPDF2 = "^2"
python = ">=3.9.16,<4"
python-dotenv = "^0.21"
python-slugify = "^7.0.0"
rapidfuzz = ">=2.13.2"
recommonmark = "^0.7"
scipy = ">=1.9.3"
seaborn = "^0.12"
sentence_transformers = "^2.2"
spacy = "*"
sphinx = "*"
toml = "*"
# torchtext = "*"
tox = "^3.25.0"
# transformers = "*"
evaluate = "*"
sacrebleu = "*"
tqdm = "*"
unidecode = "*"
# typer = "^0.4.1"
nlpia2_wikipedia = "*"
# nlpia2-wikipedia = {git = "https://gitlab.com/tangibleai/wikipedia.git", rev = "main"}
# nlpia2_wikipedia = "^1.5"
# wikipedia = { git = "https://gitlab.com/tangibleai/wikipedia.git", tag = "1.4.1" }
xmltodict = "*"

[tool.poetry.dev-dependencies]
tox = ">=3"
pytest-cov = ">=4.0"
# pytest-mock = "^3.5"
# pytest-sugar = "^0.9"
pylint = "^2.6"
pre-commit = "^2.6"
deepdiff = ">=5.0"
httpretty = ">=1.0"
zipp = { version = ">=3.4", python = ">=3.9.16" }
flatdict = ">=4.0.1"
pydocstyle = ">=5.1.1"

[tool.poetry.extras]
test = ["pytest", "pytest-cov"]
sound = ["soundex"]
# FIXME: add versions for these packages in another extras.dependencies or dev-dependencies section?
pdf = ["pymupdf", "tabula-py", "tabulate"]

[tool.black]
# https://github.com/psf/black
line-length = 80
target-version = ["py37"]

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 37
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2
src_paths = ["src", "tests"]
extend_skip = ["setup.py"]
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
line_length = 80
indent = 4
use_parentheses = true

# [tool.pytest.ini_options]
# minversion = "6.0"
# # addopts = "-ra -q"
# testpaths = [
#     "tests",
# ]


