[project]
name = "hydrogibs"
version = "0.1.9"
authors = [
  { name="axel Giboulot", email="axel.giboulot@epfl.ch" },
]
description = "A small hydrology package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/giboul/hydrogibs"
"Bug Tracker" = "https://github.com/giboul/hydrogibs/issues"